all:
	chmod +x *.sh
	cp yadmt.sh yadmt
	cp getParameterName.sh getParameterName
	cp runClassifier.sh runClassifier 
	g++ GenerateArffFiles.cpp Assert.cpp -o GenerateArffFiles
	g++ GetMetaInformationOfInputSVM.cpp Assert.cpp -o GetMetaInformationOfInputSVM
